### ISSUE TITLE
Design GUI for connection options

### ISSUE THREAD

**Issue by Graeme22** [Graeme22/VMCraft#5]
For the connection options, see #4.

### Task description
We need a in-game GUI that comes up when the user right-clicks the block. It should allow the user to create the URI specified in #4 so the connection can be launched. Likely components:
- [x] Toggle switch/radio button to choose local vs remote
- [x] Input field for username (default value root)
- [x] Input field for hostname
- [x] Input field for port
- [x] Input field for password (should show asterisks instead of password when entered)

This is a bit more involved than it might sound. We may also consider future improvements such as storing user/host names or allowing more protocols.
